name: 'BrowserStack Test'

on:
    push:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
        branches:
            - master

jobs:
    ubuntu-job:
        name: 'BrowserStack Test on Ubuntu'
        runs-on: ubuntu-latest
        steps:
            - name: 'BrowserStack Env Setup'
              uses: browserstack/github-actions/setup-env@master
              with:
                  username: ${{ secrets.BROWSERSTACK_USERNAME }}
                  access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
            - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
            - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
              with:
                  node-version: '22'
            - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
              with:
                  distribution: 'dragonwell'
                  java-version: '21'
            - run: npm ci
            - run: npm run lint
            - run: npm run build
            - run: npm install -g browserstack-node-sdk
            - name: 'BrowserStackLocal Setup'
              uses: browserstack/github-actions/setup-local@master
              with:
                  local-testing: start
                  local-identifier: random
            - name: 'Starting dev server'
              run: npm run start:dev &
            - name: 'Running test on BrowserStack'
              run: npx browserstack-node-sdk node scripts/browserstack-launcher.cjs
            - name: 'BrowserStackLocal Stop'
              uses: browserstack/github-actions/setup-local@master
              with:
                  local-testing: stop
