name: Generate GitHub release

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    release:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            contents: write
            id-token: write
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
            - run: git fetch --tags --force
            - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e
              with:
                  distribution: 'temurin'
                  java-version: '21'
            - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
              with:
                  node-version: '24'
            - run: npm ci
            - run: npm run build
              env:
                  LC_ALL: C
                  TZ: UTC
                  BUILD_TYPE: release
                  NODE_ENV: production
                  SIGNATURE_MODE: mandatory
                  LOCALES: en es nb
            - run: |
                  cd build
                  cp index.html encrypt.html
                  cp index.es.html encrypt.es.html
                  cp index.nb.html encrypt.nb.html
            - name: Release
              uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b
              with:
                  files: |
                      build/encrypt.html
                      build/encrypt.es.html
                      build/encrypt.nb.html
