name: Generate GitHub release

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
              with:
                  fetch-tags: true
            - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
              with:
                  distribution: 'temurin'
                  java-version: '21'
            - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
              with:
                  node-version: '20'
            - run: npm ci
            - run: npm run build
              env:
                  LC_ALL: C
                  TZ: UTC
                  BUILD_TYPE: release
                  NODE_ENV: production
                  SIGNATURE_MODE: mandatory
            - run: |
                  cd build
                  cp index.html encrypt.html
            - name: Release
              uses: softprops/action-gh-release@a74c6b72af54cfa997e81df42d94703d6313a2d0
              with:
                  files: build/encrypt.html
