name: Upload build assets to VirusTotal

permissions:
    contents: read

on:
    release:
        types:
            - published

jobs:
    virustotal:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        timeout-minutes: 5
        steps:
            - name: VirusTotal Scan
              uses: crazy-max/ghaction-virustotal@d34968c958ae283fe976efed637081b9f9dcf74f
              with:
                  vt_api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
                  files: |
                      *
                  update_release_body: true
